name: generate-and-commit-files

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: yarn
      - name: fetch
        run: ./run.sh
      - name: generate
        run: |
          yarn install
          yarn start
      - name: commit
        env:
          REPO: https://kobakazu0429:${{github.token}}@github.com/kobakazu0429/knct_iwsq_scrapbox_diagram.git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git remote set-url origin ${REPO}
          git checkout master
          git add .
          git diff --quiet && git diff --staged --quiet || (git commit -m "update"; git push origin master)
