name: generate-and-commit-files

on:
  schedule:
    - cron: '0 0 * * *'
  push:
  workflow_dispatch:


jobs:
  generate:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'
      - uses: ts-graphviz/setup-graphviz@v1
      - name: fetch
        run: ./run.sh
      - name: generate
        run: |
          apt update
          apt install -y --no-install-recommends graphviz graphviz-dev
          dot _work/iwsq.dot -Tsvg -o iwsq.svg
      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote set-url origin https://x-access-token:GITHUBTOKEN@github.com/{GITHUB_REPOSITORY}.git
          git checkout master
          git add .
          git diff --cached --quiet HEAD || git commit -m "update" && git status && git push origin HEAD
